In [45]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and result.

import numpy as np
import pandas as pd

# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [46]:
my_array=np.zeros(10)
my_array[4]=1
print(my_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Create a 4x4 matrix with values ranging from 0 to 15.

In [47]:
my_array=np.arange(16).reshape(4, 4)
print(my_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [48]:
arr1=np.array([[41,30,10],[6,35,23],[23,9,10]])
arr2=np.array([[4,29,2],[5,13,3],[24,16,7]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1/arr2)
print(arr1*arr2)


[[45 59 12]
 [11 48 26]
 [47 25 17]]
[[37  1  8]
 [ 1 22 20]
 [-1 -7  3]]
[[10.25        1.03448276  5.        ]
 [ 1.2         2.69230769  7.66666667]
 [ 0.95833333  0.5625      1.42857143]]
[[164 870  20]
 [ 30 455  69]
 [552 144  70]]


### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [ ]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print(arr[2:7])

[40 50 60 70]


### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [50]:
array=np.array([[15,18,20],[15,30,8],[25,60,30]])
print(np.sum(array))
print(np.mean(array))
print(np.max(array))


221
24.555555555555557
60


# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [51]:
df=pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])
print(df)

a    10
b    20
c    30
d    40
e    50
dtype: int64


### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [52]:
df=pd.read_csv(r"C:\Users\Lenovo\Documents\OmednaASS-2\python-numpy-pandas-group-b-Sirjanghimire\data\data.csv")
print(df.columns)


Index(['Name', 'Age', 'Salary'], dtype='object')


### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [53]:
df.iloc[[0, 1, 2]]

Name  Age  Salary
0    Alice   29   73193
1      Bob   53   85398
2  Charlie   36   47162

### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [54]:
df["Tax"]=0.1*df["Salary"]

#### Filter the dataframe by the column "age" whereby the age is above 36 years

In [55]:
df[df["Age"]>36]

Name  Age  Salary     Tax
1      Bob   53   85398  8539.8
5    Frank   58   69657  6965.7
6    Grace   41   85202  8520.2
7   Hannah   38   62421  6242.1
8    Isaac   50   74641  7464.1
9     Jack   47   38963  3896.3
11     Leo   49   41874  4187.4
12    Mona   56   34070  3407.0
13    Nina   49   91734  9173.4
17  Rachel   54   59900  5990.0
19    Tina   56   52054  5205.4

# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [56]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()
np.sum(sales_data["Sales"])




8500

In [57]:
# solution
np.mean(sales_data["Sales"])

1416.6666666666667

### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [58]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

print(customers.head(2), orders.head(2))

   CustomerID CustomerName
0           1        Alice
1           2          Bob    OrderID  CustomerID  Amount
0      101           1     250
1      102           2     400


In [59]:
# solution


### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [60]:
# NB: No test for this. Just an exercise for you to play around with
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

print(employees.head(2), departments.head(2))

   EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2    DeptID DeptName
0       1       HR
1       2  Finance


In [61]:
# solution


### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [62]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

Region Product  Sales
0  North       A    200
1  North       B    300

In [63]:
# solution
